package aerofsapi

import (
	"reflect"
	"testing"
)

// Test that an autogenerated application configure file unmarshals into a
// correct Authorization Client
func TestAuth_ParseAppConfig(t *testing.T) {
	fileName := "test_appconfig.json"
	secret := "b706384f-e65f-4058-9c13-e052044c408b"
	id := "f3c121ed-1beb-4b52-9145-70ca55d82af2"
	url := "share.syncfs.com"

	correctClient := AuthClient{Config: AuthConfig{Id: id, Secret: secret, AeroUrl: url}}
	authClient, err := NewAuthClient(fileName, "", "", []string{})
	if err != nil {
		t.Fatal("Unable to create new AuthClient from file : %s", err)
	}

	if !reflect.DeepEqual(correctClient, *authClient) {
		t.Fatalf("The two clients are different %v : %v", correctClient, *authClient)
	}

	t.Log("The clients are the same")
	t.Log(*authClient)
}
